version: '3.8'

services:
  nginx-proxy-web:
    image: nginx:${NGINX_IMAGE_VERSION:-stable-alpine}
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx-proxy-web
    restart: always
    ports:
      - "${IPv4:-0.0.0.0}:${DOCKER_HTTP_:-80}:80"
      - "${IPv4:-0.0.0.0}:${DOCKER_HTTPS:-443}:443"
    environment:
      SSL_POLICY: ${SSL_POLICY:-Mozilla-Modern}
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      driver: json-file
      options:
        max-size: 4m
        max-file: 10

  nginx-proxy-gen:
    image: nginxproxy/docker-gen:${DOCKER_GEN_IMAGE_VERSION:-latest}
    command: -notify-sighup nginx-proxy-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-proxy-gen
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: json-file
      options:
        max-size: 2m
        max-file: 10

  nginx-proxy-letsencrypt:
    image: nginxproxy/acme-companion:${NGINX_PROXY_COMPANION_IMAGE_VERSION:-latest}
    container_name: nginx-proxy-letsencrypt
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:rw
      - ${NGINX_FILES_PATH:-./data}/acme.sh:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy-gen
      NGINX_PROXY_CONTAINER: nginx-proxy-web
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
    logging:
      driver: json-file
      options:
        max-size: 2m
        max-file: 10
      
  ombi:
    image: linuxserver/ombi:${OMBI_IMAGE_VERSION:-latest}
    container_name: ombi
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=${OMBI_PUID:-1000}
      - PGID=${OMBI_PGID:-1000}
      - TZ=${OMBI_TZ:-America/Chicago}
      - VIRTUAL_HOST=${OMBI_HOSTNAME:-cloudrequests.yourdomain.tld}
      - LETSENCRYPT_HOST=${OMBI_HOSTNAME:-cloudrequests.yourdomain.tld}
    volumes:
      - ${OMBI_FILES_PATH:-./config/ombi}:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pull_policy: always 

networks:
  default:
    name: ${NETWORK:-proxy}
